In [12]:
import torch
import torch.nn as nn
from dotenv import load_dotenv

# load CUstomDensenet model
from src.Models.DCNN import CustomDenseNet
from src.model_training.metric_functions import all_statistics
import datasets

from src.utils.training_config import TrainingConfig
from src.utils.training_setup import load_and_prepare_test
load_dotenv()
from collections import Counter

In [7]:
model = CustomDenseNet(num_classes=5)
# load model weights
model_path = "./CustomDenseNet_Randomsplit_Dataset.pth"
model.load_state_dict(torch.load(model_path))


<All keys matched successfully>

In [8]:
config = TrainingConfig(
    dataset_location="Sam-Roggeman/SamRoggeman_Thesis_Dataset",
    batch_size=32
)
test_loader = load_and_prepare_test(
    config=config
)

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
criterion = nn.CrossEntropyLoss()
stats = all_statistics(model=model, dataloader=test_loader, device=device, criterion=criterion)

In [13]:
count = Counter(label for batch in test_loader for label in batch["labels"].tolist())
print(count)

Counter({2: 903, 3: 895, 1: 879, 0: 877, 4: 497})


In [15]:
confusion_matrix = stats["confusion_matrix"]
print(confusion_matrix)


[[264 205  95 313   0]
 [210 184 146 339   0]
 [163 255 124 361   0]
 [240 180 135 340   0]
 [136 129  45 187   0]]


In [16]:
print(sum(confusion_matrix[4]))  # Total instances of class 4

497
